pipeline:
    build:
        image: node:latest
        pull: true
        commands:
            - apt update
            - apt install -y jq curl
            - scripts/fetchMembers.sh
            - npm install
            - npm run lint
            - npm run build
        secrets: [bot_token]

    deploy:
        image: node:latest
        secrets: [now_token]
        commands:
            - npm i -g vercel
            - vercel --token "$NOW_TOKEN" --prod --confirm
